[package]
name = "wc-demo"
version = "0.1.0"
authors = ["Dave Herman <dherman@mozilla.com>"]
license = "MIT"

[dependencies]
neon = { git = "https://github.com/dherman/neon" }
rayon = { git = "https://github.com/nikomatsakis/rayon" }