[package]
name = "wc-demo"
version = "0.1.2"
authors = ["Dave Herman <dherman@mozilla.com>"]
license = "MIT"

[lib]
name = "wc_demo"
crate-type = ["dylib"]

[dependencies]
neon = "0.1"
rayon = "0.6.0" 
